[tool.poetry]
name = "adventofcode"
version = "0.1.0"
description = ""
authors = ["David Hinrichs <dvd.hnrchs@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
ipykernel = "^6.17.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
